import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { z } from "zod";
import { supabase } from "@/lib/supabase";
import { parseOrThrow } from "@/lib/validation";

// A college's structure: departments, and batches under each department. Codes are set once and never change
// (the database has no update grant for them); a batch's code (e.g. SEC-CSE-2027-B01) is generated by the database.
// Nothing is deleted: departments and batches are archived. Access is enforced by RLS: superadmin and the
// college's assigned onboarding manager can edit, support can only read.

const UNIQUE_VIOLATION = "23505";

function toError(error: { code?: string; message: string }): Error {
  if (error.code === UNIQUE_VIOLATION) {
    if (error.message.includes("departments_college_id_code_key")) return new Error("This department code is already used in this college");
    if (error.message.includes("departments_college_name_key")) return new Error("A department with this name already exists in this college");
  }
  if (error.message === "Department is archived") return new Error("This department is archived. Restore it before adding batches.");
  return new Error(error.message);
}

export interface Department {
  id: string;
  college_id: string;
  code: string;
  name: string;
  archived_at: string | null;
  created_at: string;
}

export interface Batch {
  id: string;
  college_id: string;
  department_id: string;
  number: number;
  code: string;
  graduation_year: number;
  archived_at: string | null;
  created_at: string;
}

const departmentsKey = (collegeId: string) => ["departments", collegeId];
const batchesKey = (collegeId: string) => ["batches", collegeId];

export function useDepartments(collegeId: string | null) {
  return useQuery({
    queryKey: departmentsKey(collegeId ?? ""),
    enabled: collegeId !== null,
    queryFn: async (): Promise<Department[]> => {
      const { data, error } = await supabase
        .from("departments")
        .select("id, college_id, code, name, archived_at, created_at")
        .eq("college_id", collegeId!)
        .order("code");
      if (error) throw toError(error);
      return data;
    },
  });
}

/** Every batch in a college (all departments), so the departments table can show counts without extra calls. */
export function useBatches(collegeId: string | null) {
  return useQuery({
    queryKey: batchesKey(collegeId ?? ""),
    enabled: collegeId !== null,
    queryFn: async (): Promise<Batch[]> => {
      const { data, error } = await supabase
        .from("batches")
        .select("id, college_id, department_id, number, code, graduation_year, archived_at, created_at")
        .eq("college_id", collegeId!)
        .order("graduation_year")
        .order("number");
      if (error) throw toError(error);
      return data;
    },
  });
}

// Same rule as the database's check: 2-10 capital letters or digits. Input is uppercased first.
const departmentCodeSchema = z
  .string()
  .trim()
  .toUpperCase()
  .min(1, "Department code is required")
  .regex(/^[A-Z0-9]{2,10}$/, "Department code must be 2-10 letters or digits");

const departmentNameSchema = z.string().trim().min(1, "Department name is required");

export interface DepartmentFormInput {
  /** Only used when creating; the code can't be changed afterwards, so edits ignore it. */
  code?: string;
  name: string;
}

/** Adds a department to `collegeId`, or renames one when `id` is given. */
export function useSaveDepartment(collegeId: string) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({ id, input }: { id?: string; input: DepartmentFormInput }) => {
      const name = parseOrThrow(departmentNameSchema, input.name);
      if (id) {
        const { data, error } = await supabase.from("departments").update({ name }).eq("id", id).select("id");
        if (error) throw toError(error);
        if (!data.length) throw new Error("This department can't be edited");
      } else {
        const code = parseOrThrow(departmentCodeSchema, input.code ?? "");
        const { error } = await supabase.from("departments").insert({ college_id: collegeId, code, name });
        if (error) throw toError(error);
      }
    },
    onSuccess: () => queryClient.invalidateQueries({ queryKey: departmentsKey(collegeId) }),
  });
}

const graduationYearSchema = z.coerce
  .number({ message: "Graduation year is required" })
  .int("Enter a year like 2027")
  .min(2000, "Enter a year between 2000 and 2100")
  .max(2100, "Enter a year between 2000 and 2100");

/**
 * Adds a batch (a section of one year's intake) to a department. The database numbers it within that year and
 * builds its code, e.g. SEC-CSE-2027-B02. The year is part of the code, so batches can't be edited afterwards,
 * only archived.
 */
export function useAddBatch(collegeId: string) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({ departmentId, graduationYear }: { departmentId: string; graduationYear: string }) => {
      if (!graduationYear.trim()) throw new Error("Graduation year is required");
      const graduation_year = parseOrThrow(graduationYearSchema, graduationYear);
      const { error } = await supabase.from("batches").insert({ department_id: departmentId, graduation_year });
      if (error) throw toError(error);
    },
    onSuccess: () => queryClient.invalidateQueries({ queryKey: batchesKey(collegeId) }),
  });
}

/** Archive or restore a department or batch. The database stamps who did it and when. */
export function useSetArchived(collegeId: string) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({ table, id, archived }: { table: "departments" | "batches"; id: string; archived: boolean }) => {
      const { data, error } = await supabase
        .from(table)
        .update({ archived_at: archived ? new Date().toISOString() : null })
        .eq("id", id)
        .select("id");
      if (error) throw toError(error);
      if (!data.length) throw new Error("This can't be changed");
    },
    onSuccess: (_data, { table }) =>
      queryClient.invalidateQueries({ queryKey: table === "departments" ? departmentsKey(collegeId) : batchesKey(collegeId) }),
  });
}
