// College-side accounts: students, faculty and TPOs. One endpoint.
// Students:
//   create          { batch_id, full_name, email, roll_number, phone? }
//   import          { batch_id, students: [{ row, full_name, email, roll_number, phone? }] }   (all or nothing)
//   reset_password  { student_id }                        (back to the batch code without dashes)
//   set_status      { student_id, status: "active" | "inactive" }
// A student signs in with email + password. The first password is their batch code without dashes (SEC-CSE-2028-B01
// gives SECCSE2028B01); changing it later is up to the student (the app asks for 8+ characters when they do).
// Faculty:
//   faculty_create          { college_id, full_name, email, phone?, department_id?, faculty_role_id?, password }
//   faculty_import          { college_id, faculty: [{ row, full_name, email, phone?, department_code?, faculty_role? }] }
//                           (all or nothing; returns each new account's faculty ID and a generated password, once)
//   faculty_update          { faculty_id, full_name, phone?, department_id?, faculty_role_id? }
//                           (replaces all of these, so a field left out is cleared; email and faculty ID never change)
//   faculty_reset_password  { faculty_id, password }
//   faculty_set_status      { faculty_id, status: "active" | "inactive" }
//   faculty_assign_batches  { faculty_id, batch_ids: [...] }   (all or nothing)
//   faculty_unassign_batch  { faculty_id, batch_id }           (kept on record, not deleted)
// Faculty passwords come from the app's generator (8-72 characters); the faculty ID (e.g. SEC-F7K2) is generated by
// the database. Department and role are linked records only: ids here, department code / role name in an import.
// TPOs (any number per college; no import):
//   tpo_create              { college_id, full_name, email, phone?, designation_id?, password }   (new login)
//   tpo_create_from_faculty { faculty_id, designation_id? }   (same login as the faculty member; no new password)
//   tpo_update              { tpo_id, full_name, phone?, designation_id? }
//                           (replaces all of these; name and phone also change on the same person's faculty row)
//   tpo_reset_password      { tpo_id, password }   (a faculty+TPO login has one password, so this resets both)
//   tpo_set_status          { tpo_id, status: "active" | "inactive" }
// The TPO ID (e.g. SEC-T7K2) is generated by the database. A login that is both faculty and TPO keeps signing in
// while either of its roles is active; deactivating one role leaves the other working.
// Nothing here deletes accounts (an import that fails part-way removes only the accounts it just made).
// Caller must be an active superadmin (any college) or an onboarding manager assigned to the account's college.
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
const anonKey = Deno.env.get("SUPABASE_ANON_KEY")!;
const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const MAX_ROLL_LENGTH = 30;
const MIN_PASSWORD_LENGTH = 8;
const MAX_PASSWORD_LENGTH = 72;
const GENERATED_PASSWORD_LENGTH = 12;
// Look-alikes (0/O, 1/l/I) left out so a password read off a screen is typed correctly.
const PASSWORD_CHARS = "ABCDEFGHJKMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789";
const MAX_IMPORT_ROWS = 500;
const CREATE_CONCURRENCY = 5;
// Supabase has no "disable user" flag; a very long ban blocks sign-in and token refresh.
const BAN_FOREVER = "876000h";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

const fail = (status: number, error: string) => json({ error }, status);

const str = (v: unknown) => (typeof v === "string" ? v.trim() : "");

/** A batch's starting password: its code without dashes (always longer than Supabase's 6-character minimum). */
const batchPassword = (batchCode: string) => batchCode.replace(/-/g, "");

type Admin = ReturnType<typeof createClient>;
type UserClient = ReturnType<typeof createClient>;

interface Caller {
  id: string;
  isSuperadmin: boolean;
  client: UserClient;
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });
  if (req.method !== "POST") return fail(405, "Method not allowed");

  const authHeader = req.headers.get("Authorization");
  if (!authHeader) return fail(401, "Missing authorization");

  // Identify the caller with their own JWT, then require an active superadmin or onboarding manager.
  const userClient = createClient(supabaseUrl, anonKey, { global: { headers: { Authorization: authHeader } } });
  const { data: userData, error: userError } = await userClient.auth.getUser();
  if (userError || !userData.user) return fail(401, "Invalid session");

  const { data: isSuperadmin, error: superError } = await userClient.rpc("is_superadmin");
  if (superError) return fail(500, "Could not verify permissions");
  if (!isSuperadmin) {
    const { data: isManager, error: managerError } = await userClient.rpc("has_role", { p_role_id: "onboarding_manager" });
    if (managerError) return fail(500, "Could not verify permissions");
    if (!isManager) return fail(403, "Not authorized");
  }
  const caller: Caller = { id: userData.user.id, isSuperadmin: !!isSuperadmin, client: userClient };

  let body: Record<string, unknown>;
  try {
    body = await req.json();
  } catch {
    return fail(400, "Invalid JSON");
  }

  const admin = createClient(supabaseUrl, serviceKey, { auth: { autoRefreshToken: false, persistSession: false } });

  switch (body.action) {
    case "create":
      return await createOne(admin, caller, body);
    case "import":
      return await importMany(admin, caller, body);
    case "reset_password":
      return await resetPassword(admin, caller, body);
    case "set_status":
      return await setStatus(admin, caller, body);
    case "faculty_create":
      return await createFaculty(admin, caller, body);
    case "faculty_import":
      return await importFaculty(admin, caller, body);
    case "faculty_update":
      return await updateFaculty(admin, caller, body);
    case "faculty_reset_password":
      return await resetFacultyPassword(admin, caller, body);
    case "faculty_set_status":
      return await setFacultyStatus(admin, caller, body);
    case "faculty_assign_batches":
      return await assignBatches(admin, caller, body);
    case "faculty_unassign_batch":
      return await unassignBatch(admin, caller, body);
    case "tpo_create":
      return await createTpo(admin, caller, body);
    case "tpo_create_from_faculty":
      return await createTpoFromFaculty(admin, caller, body);
    case "tpo_update":
      return await updateTpo(admin, caller, body);
    case "tpo_reset_password":
      return await resetTpoPassword(admin, caller, body);
    case "tpo_set_status":
      return await setTpoStatus(admin, caller, body);
    default:
      return fail(400, "Unknown action");
  }
});

/** Superadmin may act on any college; a manager only on colleges assigned to them. */
async function canManageCollege(caller: Caller, collegeId: string): Promise<boolean> {
  if (caller.isSuperadmin) return true;
  const { data, error } = await caller.client.rpc("is_assigned_college", { p_college_id: collegeId });
  return !error && data === true;
}

/** Looks up the batch and checks the caller may add students to it. Returns an error response or the batch. */
async function loadBatch(admin: Admin, caller: Caller, batchId: string) {
  if (!batchId) return { error: fail(400, "batch_id is required") };
  const { data: batch, error } = await admin.from("batches").select("id, college_id, code, archived_at").eq("id", batchId).maybeSingle();
  if (error) return { error: fail(500, "Could not load batch") };
  if (!batch || !(await canManageCollege(caller, batch.college_id as string))) return { error: fail(404, "Batch not found") };
  if (batch.archived_at) return { error: fail(400, "This batch is archived. Restore it before adding students.") };
  return { batch: batch as { id: string; college_id: string; code: string } };
}

interface StudentInput {
  row: number;
  full_name: string;
  email: string;
  roll_number: string;
  phone: string;
}

function readStudent(raw: Record<string, unknown>, row: number): StudentInput {
  return {
    row,
    full_name: str(raw.full_name),
    email: str(raw.email).toLowerCase(),
    roll_number: str(raw.roll_number),
    phone: str(raw.phone),
  };
}

/** Field-level problems with one student, before touching the database. */
function validate(s: StudentInput): string[] {
  const problems: string[] = [];
  if (!s.full_name) problems.push("Full name is required");
  if (!EMAIL_RE.test(s.email)) problems.push("A valid email is required");
  if (!s.roll_number) problems.push("Roll number is required");
  else if (s.roll_number.length > MAX_ROLL_LENGTH) problems.push(`Roll number can be at most ${MAX_ROLL_LENGTH} characters`);
  return problems;
}

/** Emails (lower-cased) already used by any account: staff, student, faculty or TPO. */
async function emailsInUse(admin: Admin, emails: string[]): Promise<Set<string>> {
  const results = await Promise.all(
    ["students", "profiles", "faculty", "tpo"].map((table) => admin.from(table).select("email").in("email", emails)),
  );
  if (results.some((r) => r.error)) throw new Error("Could not check existing accounts");
  return new Set(results.flatMap((r) => r.data!).map((r) => (r.email as string).toLowerCase()));
}

/** Emails already used by any account, and roll numbers already used in this college (lower-cased). */
async function existingConflicts(admin: Admin, collegeId: string, emails: string[]) {
  const [used, rolls] = await Promise.all([
    emailsInUse(admin, emails),
    admin.from("students").select("roll_number").eq("college_id", collegeId),
  ]);
  if (rolls.error) throw new Error("Could not check existing accounts");
  return {
    emails: used,
    rolls: new Set(rolls.data.map((r) => (r.roll_number as string).toLowerCase())),
  };
}

/** Creates the auth user and the student row; removes the auth user again if the row can't be written. */
async function createAccount(
  admin: Admin,
  callerId: string,
  batch: { id: string; code: string },
  s: StudentInput,
): Promise<{ id?: string; error?: string }> {
  const { data: created, error: createError } = await admin.auth.admin.createUser({
    email: s.email,
    password: batchPassword(batch.code),
    email_confirm: true,
  });
  if (createError || !created.user) {
    const exists = createError?.code === "email_exists" || /already/i.test(createError?.message ?? "");
    return { error: exists ? "A user with this email already exists" : (createError?.message ?? "Could not create account") };
  }
  const { error: rowError } = await admin.rpc("college_create_student", {
    p_id: created.user.id,
    p_batch_id: batch.id,
    p_full_name: s.full_name,
    p_email: s.email,
    p_roll_number: s.roll_number,
    p_phone: s.phone,
    p_created_by: callerId,
  });
  if (rowError) {
    await admin.auth.admin.deleteUser(created.user.id);
    const message = rowError.message;
    if (message.includes("students_college_roll_key")) return { error: "This roll number is already used in this college" };
    if (message.includes("students_email_key")) return { error: "A user with this email already exists" };
    if (message === "Batch is archived") return { error: "This batch is archived. Restore it before adding students." };
    return { error: "Could not create student" };
  }
  return { id: created.user.id };
}

async function createOne(admin: Admin, caller: Caller, body: Record<string, unknown>) {
  const loaded = await loadBatch(admin, caller, str(body.batch_id));
  if (loaded.error) return loaded.error;
  const student = readStudent(body, 1);
  const problems = validate(student);
  if (problems.length) return fail(400, problems[0]);

  let conflicts;
  try {
    conflicts = await existingConflicts(admin, loaded.batch.college_id, [student.email]);
  } catch (e) {
    return fail(500, (e as Error).message);
  }
  if (conflicts.emails.has(student.email)) return fail(409, "A user with this email already exists");
  if (conflicts.rolls.has(student.roll_number.toLowerCase())) return fail(409, "This roll number is already used in this college");

  const result = await createAccount(admin, caller.id, loaded.batch, student);
  if (result.error) return fail(409, result.error);
  return json({ id: result.id }, 201);
}

// All or nothing: every row is checked first (fields, duplicates inside the file, clashes with existing accounts);
// if anything is wrong, nothing is created and every problem is returned by row. If creation still fails part-way
// (e.g. an email taken a moment ago), the accounts made so far are removed again.
async function importMany(admin: Admin, caller: Caller, body: Record<string, unknown>) {
  const loaded = await loadBatch(admin, caller, str(body.batch_id));
  if (loaded.error) return loaded.error;
  if (!Array.isArray(body.students) || body.students.length === 0) return fail(400, "No students to import");
  if (body.students.length > MAX_IMPORT_ROWS) return fail(400, `At most ${MAX_IMPORT_ROWS} students per import`);

  const students = (body.students as Record<string, unknown>[]).map((raw, i) =>
    readStudent(raw ?? {}, typeof raw?.row === "number" ? raw.row : i + 2),
  );

  let conflicts;
  try {
    conflicts = await existingConflicts(admin, loaded.batch.college_id, students.map((s) => s.email).filter(Boolean));
  } catch (e) {
    return fail(500, (e as Error).message);
  }

  const errors: { row: number; message: string }[] = [];
  const seenEmails = new Map<string, number>();
  const seenRolls = new Map<string, number>();
  for (const s of students) {
    const problems = validate(s);
    const rollKey = s.roll_number.toLowerCase();
    if (s.email && seenEmails.has(s.email)) problems.push(`Same email as row ${seenEmails.get(s.email)}`);
    else if (conflicts.emails.has(s.email)) problems.push("A user with this email already exists");
    if (rollKey && seenRolls.has(rollKey)) problems.push(`Same roll number as row ${seenRolls.get(rollKey)}`);
    else if (conflicts.rolls.has(rollKey)) problems.push("This roll number is already used in this college");
    if (s.email && !seenEmails.has(s.email)) seenEmails.set(s.email, s.row);
    if (rollKey && !seenRolls.has(rollKey)) seenRolls.set(rollKey, s.row);
    for (const message of problems) errors.push({ row: s.row, message });
  }
  if (errors.length) return json({ error: "Fix the rows below and import again. Nothing was imported.", errors }, 400);

  const createdIds: string[] = [];
  for (let i = 0; i < students.length; i += CREATE_CONCURRENCY) {
    const chunk = students.slice(i, i + CREATE_CONCURRENCY);
    const results = await Promise.all(chunk.map((s) => createAccount(admin, caller.id, loaded.batch, s)));
    results.forEach((r) => r.id && createdIds.push(r.id));
    const failedAt = results.findIndex((r) => r.error);
    if (failedAt !== -1) {
      await removeAccounts(admin, createdIds);
      return json(
        {
          error: "Import stopped and was undone. Nothing was imported.",
          errors: [{ row: chunk[failedAt].row, message: results[failedAt].error! }],
        },
        409,
      );
    }
  }
  return json({ created: createdIds.length }, 201);
}

/** Undo for a failed import only: removes accounts this request just created. */
async function removeAccounts(admin: Admin, ids: string[]) {
  if (!ids.length) return;
  await admin.from("students").delete().in("id", ids);
  await Promise.all(ids.map((id) => admin.auth.admin.deleteUser(id)));
}

/** Looks up the student and checks the caller may manage them. */
async function loadStudent(admin: Admin, caller: Caller, studentId: string) {
  if (!studentId) return { error: fail(400, "student_id is required") };
  const { data, error } = await admin
    .from("students")
    .select("id, college_id, status, batches(code)")
    .eq("id", studentId)
    .maybeSingle();
  if (error) return { error: fail(500, "Could not load student") };
  if (!data || !(await canManageCollege(caller, data.college_id as string))) return { error: fail(404, "Student not found") };
  const batch = data.batches as unknown as { code: string };
  return { student: { id: data.id as string, college_id: data.college_id as string, status: data.status as string, batch_code: batch.code } };
}

async function resetPassword(admin: Admin, caller: Caller, body: Record<string, unknown>) {
  const loaded = await loadStudent(admin, caller, str(body.student_id));
  if (loaded.error) return loaded.error;
  const { error } = await admin.auth.admin.updateUserById(loaded.student.id, { password: batchPassword(loaded.student.batch_code) });
  if (error) return fail(400, error.message);
  return json({ ok: true });
}

async function setStatus(admin: Admin, caller: Caller, body: Record<string, unknown>) {
  const status = body.status;
  if (status !== "active" && status !== "inactive") return fail(400, "status must be active or inactive");
  const loaded = await loadStudent(admin, caller, str(body.student_id));
  if (loaded.error) return loaded.error;
  return await switchStatus(admin, "students", loaded.student.id, loaded.student.status, status);
}

type AccountTable = "students" | "faculty" | "tpo";
const ACCOUNT_TABLES: AccountTable[] = ["students", "faculty", "tpo"];

/**
 * Sets the account row's status and bans/unbans sign-in to match; puts the old status back if the ban fails.
 * One login can be both faculty and TPO, so sign-in is blocked only when none of its accounts is active any more.
 */
async function switchStatus(admin: Admin, table: AccountTable, id: string, previous: string, status: string) {
  const { error: updateError } = await admin.from(table).update({ status }).eq("id", id);
  if (updateError) return fail(500, "Could not update status");

  let signInOpen = status === "active";
  if (!signInOpen) {
    const others = await Promise.all(
      ACCOUNT_TABLES.filter((t) => t !== table).map((t) =>
        admin.from(t).select("id").eq("id", id).eq("status", "active").maybeSingle()
      ),
    );
    if (others.some((r) => r.error)) {
      await admin.from(table).update({ status: previous }).eq("id", id);
      return fail(500, "Could not update sign-in access");
    }
    signInOpen = others.some((r) => r.data);
  }

  const { error: banError } = await admin.auth.admin.updateUserById(id, {
    ban_duration: signInOpen ? "none" : BAN_FOREVER,
  });
  if (banError) {
    await admin.from(table).update({ status: previous }).eq("id", id);
    return fail(500, "Could not update sign-in access");
  }
  return json({ ok: true, status });
}

// ---------------------------------------------------------------------------------------------------------------------
// Faculty
// ---------------------------------------------------------------------------------------------------------------------

/** A random password from PASSWORD_CHARS (rejection sampling, so every character is equally likely). */
function generatePassword(): string {
  const out: string[] = [];
  const limit = 256 - (256 % PASSWORD_CHARS.length);
  while (out.length < GENERATED_PASSWORD_LENGTH) {
    for (const byte of crypto.getRandomValues(new Uint8Array(32))) {
      if (byte < limit && out.length < GENERATED_PASSWORD_LENGTH) out.push(PASSWORD_CHARS[byte % PASSWORD_CHARS.length]);
    }
  }
  return out.join("");
}

function passwordProblem(password: string): string | null {
  if (password.length < MIN_PASSWORD_LENGTH) return `Password must be at least ${MIN_PASSWORD_LENGTH} characters`;
  if (password.length > MAX_PASSWORD_LENGTH) return `Password can be at most ${MAX_PASSWORD_LENGTH} characters`;
  return null;
}

/** An optional id from the request: undefined/null/"" mean none. */
const optionalId = (v: unknown) => (typeof v === "string" && v.trim() ? v.trim() : null);

/** Looks up the college and checks the caller may manage it. */
async function loadCollege(admin: Admin, caller: Caller, collegeId: string) {
  if (!collegeId) return { error: fail(400, "college_id is required") };
  if (!UUID_RE.test(collegeId)) return { error: fail(404, "College not found") };
  const { data, error } = await admin.from("colleges").select("id").eq("id", collegeId).maybeSingle();
  if (error) return { error: fail(500, "Could not load college") };
  if (!data || !(await canManageCollege(caller, data.id as string))) return { error: fail(404, "College not found") };
  return { college: { id: data.id as string } };
}

/** Looks up the faculty member and checks the caller may manage them. */
async function loadFaculty(admin: Admin, caller: Caller, facultyId: string) {
  if (!facultyId) return { error: fail(400, "faculty_id is required") };
  if (!UUID_RE.test(facultyId)) return { error: fail(404, "Faculty not found") };
  const { data, error } = await admin.from("faculty").select("id, college_id, status").eq("id", facultyId).maybeSingle();
  if (error) return { error: fail(500, "Could not load faculty") };
  if (!data || !(await canManageCollege(caller, data.college_id as string))) return { error: fail(404, "Faculty not found") };
  return { faculty: { id: data.id as string, college_id: data.college_id as string, status: data.status as string } };
}

interface FacultyInput {
  row: number;
  full_name: string;
  email: string;
  phone: string;
  department_id: string | null;
  faculty_role_id: string | null;
}

function validateFaculty(f: FacultyInput): string[] {
  const problems: string[] = [];
  if (!f.full_name) problems.push("Full name is required");
  if (!EMAIL_RE.test(f.email)) problems.push("A valid email is required");
  return problems;
}

/** Readable messages for the errors the faculty database functions raise on purpose; anything else stays generic. */
function facultyDbError(message: string, fallback: string): string {
  if (message.includes("faculty_email_key")) return "A user with this email already exists";
  if (message === "Department not found") return "Department not found in this college";
  if (message === "Faculty role not found") return "Current role not found";
  if (message === "College not found" || message === "Faculty not found") return message;
  return fallback;
}

/** Creates the auth user and the faculty row; removes the auth user again if the row can't be written. */
async function createFacultyAccount(
  admin: Admin,
  callerId: string,
  collegeId: string,
  f: FacultyInput,
  password: string,
): Promise<{ id?: string; code?: string; error?: string }> {
  const { data: created, error: createError } = await admin.auth.admin.createUser({
    email: f.email,
    password,
    email_confirm: true,
  });
  if (createError || !created.user) {
    const exists = createError?.code === "email_exists" || /already/i.test(createError?.message ?? "");
    return { error: exists ? "A user with this email already exists" : (createError?.message ?? "Could not create account") };
  }
  const { data: code, error: rowError } = await admin.rpc("college_create_faculty", {
    p_id: created.user.id,
    p_college_id: collegeId,
    p_full_name: f.full_name,
    p_email: f.email,
    p_phone: f.phone,
    p_department_id: f.department_id,
    p_faculty_role_id: f.faculty_role_id,
    p_created_by: callerId,
  });
  if (rowError) {
    await admin.auth.admin.deleteUser(created.user.id);
    return { error: facultyDbError(rowError.message, "Could not create faculty") };
  }
  return { id: created.user.id, code: code as string };
}

async function createFaculty(admin: Admin, caller: Caller, body: Record<string, unknown>) {
  const loaded = await loadCollege(admin, caller, str(body.college_id));
  if (loaded.error) return loaded.error;
  const faculty: FacultyInput = {
    row: 1,
    full_name: str(body.full_name),
    email: str(body.email).toLowerCase(),
    phone: str(body.phone),
    department_id: optionalId(body.department_id),
    faculty_role_id: optionalId(body.faculty_role_id),
  };
  const problems = validateFaculty(faculty);
  if (faculty.department_id && !UUID_RE.test(faculty.department_id)) problems.push("Department not found in this college");
  const password = typeof body.password === "string" ? body.password : "";
  const badPassword = passwordProblem(password);
  if (badPassword) problems.push(badPassword);
  if (problems.length) return fail(400, problems[0]);

  try {
    if ((await emailsInUse(admin, [faculty.email])).has(faculty.email)) return fail(409, "A user with this email already exists");
  } catch (e) {
    return fail(500, (e as Error).message);
  }

  const result = await createFacultyAccount(admin, caller.id, loaded.college.id, faculty, password);
  if (result.error) return fail(result.error.startsWith("A user") ? 409 : 400, result.error);
  return json({ id: result.id, code: result.code }, 201);
}

// All or nothing, like the student import. Department and role come as a department code and a role name (or id),
// matched against the college's departments and the faculty role list. Every account gets a generated password,
// returned once in the response for the manager to hand out.
async function importFaculty(admin: Admin, caller: Caller, body: Record<string, unknown>) {
  const loaded = await loadCollege(admin, caller, str(body.college_id));
  if (loaded.error) return loaded.error;
  const collegeId = loaded.college.id;
  if (!Array.isArray(body.faculty) || body.faculty.length === 0) return fail(400, "No faculty to import");
  if (body.faculty.length > MAX_IMPORT_ROWS) return fail(400, `At most ${MAX_IMPORT_ROWS} faculty per import`);

  const [departments, roles] = await Promise.all([
    admin.from("departments").select("id, code").eq("college_id", collegeId).is("archived_at", null),
    admin.from("faculty_roles").select("id, label").eq("is_active", true),
  ]);
  if (departments.error || roles.error) return fail(500, "Could not load departments and roles");
  const departmentByCode = new Map(departments.data.map((d) => [(d.code as string).toUpperCase(), d.id as string]));
  const roleByName = new Map<string, string>();
  for (const r of roles.data) {
    roleByName.set((r.id as string).toLowerCase(), r.id as string);
    roleByName.set((r.label as string).trim().toLowerCase(), r.id as string);
  }

  const errors: { row: number; message: string }[] = [];
  const rows = (body.faculty as Record<string, unknown>[]).map((raw, i) => {
    raw = raw ?? {};
    const row = typeof raw.row === "number" ? raw.row : i + 2;
    const departmentCode = str(raw.department_code).toUpperCase();
    const roleName = str(raw.faculty_role).toLowerCase();
    const f: FacultyInput = {
      row,
      full_name: str(raw.full_name),
      email: str(raw.email).toLowerCase(),
      phone: str(raw.phone),
      department_id: departmentCode ? (departmentByCode.get(departmentCode) ?? null) : null,
      faculty_role_id: roleName ? (roleByName.get(roleName) ?? null) : null,
    };
    const problems = validateFaculty(f);
    if (departmentCode && !f.department_id) problems.push(`Department "${str(raw.department_code)}" not found in this college`);
    if (roleName && !f.faculty_role_id) problems.push(`Current role "${str(raw.faculty_role)}" not found`);
    for (const message of problems) errors.push({ row, message });
    return f;
  });

  let used: Set<string>;
  try {
    used = await emailsInUse(admin, rows.map((f) => f.email).filter(Boolean));
  } catch (e) {
    return fail(500, (e as Error).message);
  }
  const seenEmails = new Map<string, number>();
  for (const f of rows) {
    if (!f.email) continue;
    if (seenEmails.has(f.email)) errors.push({ row: f.row, message: `Same email as row ${seenEmails.get(f.email)}` });
    else if (used.has(f.email)) errors.push({ row: f.row, message: "A user with this email already exists" });
    if (!seenEmails.has(f.email)) seenEmails.set(f.email, f.row);
  }
  if (errors.length) {
    errors.sort((a, b) => a.row - b.row);
    return json({ error: "Fix the rows below and import again. Nothing was imported.", errors }, 400);
  }

  const accounts: { row: number; full_name: string; email: string; code: string; password: string }[] = [];
  const createdIds: string[] = [];
  for (let i = 0; i < rows.length; i += CREATE_CONCURRENCY) {
    const chunk = rows.slice(i, i + CREATE_CONCURRENCY);
    const passwords = chunk.map(() => generatePassword());
    const results = await Promise.all(chunk.map((f, j) => createFacultyAccount(admin, caller.id, collegeId, f, passwords[j])));
    results.forEach((r, j) => {
      if (!r.id) return;
      createdIds.push(r.id);
      accounts.push({ row: chunk[j].row, full_name: chunk[j].full_name, email: chunk[j].email, code: r.code!, password: passwords[j] });
    });
    const failedAt = results.findIndex((r) => r.error);
    if (failedAt !== -1) {
      await removeFacultyAccounts(admin, createdIds);
      return json(
        {
          error: "Import stopped and was undone. Nothing was imported.",
          errors: [{ row: chunk[failedAt].row, message: results[failedAt].error! }],
        },
        409,
      );
    }
  }
  return json({ created: accounts.length, accounts }, 201);
}

/** Undo for a failed import only: removes accounts this request just created (they have no assignments yet). */
async function removeFacultyAccounts(admin: Admin, ids: string[]) {
  if (!ids.length) return;
  await admin.from("faculty").delete().in("id", ids);
  await Promise.all(ids.map((id) => admin.auth.admin.deleteUser(id)));
}

async function updateFaculty(admin: Admin, caller: Caller, body: Record<string, unknown>) {
  const loaded = await loadFaculty(admin, caller, str(body.faculty_id));
  if (loaded.error) return loaded.error;
  const fullName = str(body.full_name);
  if (!fullName) return fail(400, "Full name is required");
  const departmentId = optionalId(body.department_id);
  if (departmentId && !UUID_RE.test(departmentId)) return fail(400, "Department not found in this college");

  const { error } = await admin.rpc("college_update_faculty", {
    p_id: loaded.faculty.id,
    p_full_name: fullName,
    p_phone: str(body.phone),
    p_department_id: departmentId,
    p_faculty_role_id: optionalId(body.faculty_role_id),
  });
  if (error) return fail(400, facultyDbError(error.message, "Could not update faculty"));
  return json({ ok: true });
}

async function resetFacultyPassword(admin: Admin, caller: Caller, body: Record<string, unknown>) {
  const loaded = await loadFaculty(admin, caller, str(body.faculty_id));
  if (loaded.error) return loaded.error;
  const password = typeof body.password === "string" ? body.password : "";
  const badPassword = passwordProblem(password);
  if (badPassword) return fail(400, badPassword);
  const { error } = await admin.auth.admin.updateUserById(loaded.faculty.id, { password });
  if (error) return fail(400, error.message);
  return json({ ok: true });
}

async function setFacultyStatus(admin: Admin, caller: Caller, body: Record<string, unknown>) {
  const status = body.status;
  if (status !== "active" && status !== "inactive") return fail(400, "status must be active or inactive");
  const loaded = await loadFaculty(admin, caller, str(body.faculty_id));
  if (loaded.error) return loaded.error;
  return await switchStatus(admin, "faculty", loaded.faculty.id, loaded.faculty.status, status);
}

// Messages college_assign_faculty_batches / college_unassign_faculty_batch raise on purpose (safe to show as-is).
const ASSIGNMENT_ERRORS = [
  /^Faculty is inactive$/,
  /^No batches to assign$/,
  /^A batch is listed more than once$/,
  /^Batch not found$/,
  /^Archived batch: /,
  /^Already assigned: /,
  /^Assignment not found$/,
];

async function assignBatches(admin: Admin, caller: Caller, body: Record<string, unknown>) {
  const loaded = await loadFaculty(admin, caller, str(body.faculty_id));
  if (loaded.error) return loaded.error;
  if (!Array.isArray(body.batch_ids) || body.batch_ids.length === 0) return fail(400, "No batches to assign");
  const batchIds = body.batch_ids.map(str);
  if (batchIds.some((id) => !UUID_RE.test(id))) return fail(400, "Batch not found");

  const { data, error } = await admin.rpc("college_assign_faculty_batches", {
    p_faculty_id: loaded.faculty.id,
    p_batch_ids: batchIds,
    p_assigned_by: caller.id,
  });
  if (error) {
    const known = ASSIGNMENT_ERRORS.some((re) => re.test(error.message));
    return fail(known ? 400 : 500, known ? error.message : "Could not assign batches");
  }
  return json({ assigned: data }, 201);
}

async function unassignBatch(admin: Admin, caller: Caller, body: Record<string, unknown>) {
  const loaded = await loadFaculty(admin, caller, str(body.faculty_id));
  if (loaded.error) return loaded.error;
  const batchId = str(body.batch_id);
  if (!UUID_RE.test(batchId)) return fail(404, "Assignment not found");

  const { error } = await admin.rpc("college_unassign_faculty_batch", {
    p_faculty_id: loaded.faculty.id,
    p_batch_id: batchId,
    p_unassigned_by: caller.id,
  });
  if (error) {
    if (error.message === "Assignment not found") return fail(404, error.message);
    return fail(500, "Could not unassign batch");
  }
  return json({ ok: true });
}

// ---------------------------------------------------------------------------------------------------------------------
// TPO
// ---------------------------------------------------------------------------------------------------------------------

/** Looks up the TPO and checks the caller may manage them. */
async function loadTpo(admin: Admin, caller: Caller, tpoId: string) {
  if (!tpoId) return { error: fail(400, "tpo_id is required") };
  if (!UUID_RE.test(tpoId)) return { error: fail(404, "TPO not found") };
  const { data, error } = await admin.from("tpo").select("id, college_id, status").eq("id", tpoId).maybeSingle();
  if (error) return { error: fail(500, "Could not load TPO") };
  if (!data || !(await canManageCollege(caller, data.college_id as string))) return { error: fail(404, "TPO not found") };
  return { tpo: { id: data.id as string, college_id: data.college_id as string, status: data.status as string } };
}

/** Readable messages for the errors the TPO database functions raise on purpose; anything else stays generic. */
function tpoDbError(message: string, fallback: string): string {
  if (message.includes("tpo_email_key")) return "A user with this email already exists";
  if (message.includes("tpo_pkey") || message === "Already a TPO") return "This faculty member is already a TPO";
  if (message === "Designation not found") return message;
  if (message === "Faculty is inactive") return "This faculty member is inactive. Reactivate them first.";
  if (message === "College not found" || message === "Faculty not found" || message === "TPO not found") return message;
  return fallback;
}

async function createTpo(admin: Admin, caller: Caller, body: Record<string, unknown>) {
  const loaded = await loadCollege(admin, caller, str(body.college_id));
  if (loaded.error) return loaded.error;
  const fullName = str(body.full_name);
  const email = str(body.email).toLowerCase();
  const problems: string[] = [];
  if (!fullName) problems.push("Full name is required");
  if (!EMAIL_RE.test(email)) problems.push("A valid email is required");
  const password = typeof body.password === "string" ? body.password : "";
  const badPassword = passwordProblem(password);
  if (badPassword) problems.push(badPassword);
  if (problems.length) return fail(400, problems[0]);

  try {
    if ((await emailsInUse(admin, [email])).has(email)) return fail(409, "A user with this email already exists");
  } catch (e) {
    return fail(500, (e as Error).message);
  }

  const { data: created, error: createError } = await admin.auth.admin.createUser({ email, password, email_confirm: true });
  if (createError || !created.user) {
    const exists = createError?.code === "email_exists" || /already/i.test(createError?.message ?? "");
    return fail(exists ? 409 : 400, exists ? "A user with this email already exists" : (createError?.message ?? "Could not create account"));
  }
  const { data: code, error: rowError } = await admin.rpc("college_create_tpo", {
    p_id: created.user.id,
    p_college_id: loaded.college.id,
    p_full_name: fullName,
    p_email: email,
    p_phone: str(body.phone),
    p_designation_id: optionalId(body.designation_id),
    p_created_by: caller.id,
  });
  if (rowError) {
    await admin.auth.admin.deleteUser(created.user.id);
    const message = tpoDbError(rowError.message, "Could not create TPO");
    return fail(message.startsWith("A user") ? 409 : 400, message);
  }
  return json({ id: created.user.id, code }, 201);
}

// Makes an existing faculty member a TPO of the same college on their existing login. No new account or password:
// they sign in as before and get both roles.
async function createTpoFromFaculty(admin: Admin, caller: Caller, body: Record<string, unknown>) {
  const loaded = await loadFaculty(admin, caller, str(body.faculty_id));
  if (loaded.error) return loaded.error;
  const { data: code, error } = await admin.rpc("college_make_faculty_tpo", {
    p_faculty_id: loaded.faculty.id,
    p_designation_id: optionalId(body.designation_id),
    p_created_by: caller.id,
  });
  if (error) {
    const message = tpoDbError(error.message, "Could not make this faculty member a TPO");
    return fail(message.startsWith("This faculty member is already") ? 409 : 400, message);
  }
  return json({ id: loaded.faculty.id, code }, 201);
}

async function updateTpo(admin: Admin, caller: Caller, body: Record<string, unknown>) {
  const loaded = await loadTpo(admin, caller, str(body.tpo_id));
  if (loaded.error) return loaded.error;
  const fullName = str(body.full_name);
  if (!fullName) return fail(400, "Full name is required");

  const { error } = await admin.rpc("college_update_tpo", {
    p_id: loaded.tpo.id,
    p_full_name: fullName,
    p_phone: str(body.phone),
    p_designation_id: optionalId(body.designation_id),
  });
  if (error) return fail(400, tpoDbError(error.message, "Could not update TPO"));
  return json({ ok: true });
}

async function resetTpoPassword(admin: Admin, caller: Caller, body: Record<string, unknown>) {
  const loaded = await loadTpo(admin, caller, str(body.tpo_id));
  if (loaded.error) return loaded.error;
  const password = typeof body.password === "string" ? body.password : "";
  const badPassword = passwordProblem(password);
  if (badPassword) return fail(400, badPassword);
  const { error } = await admin.auth.admin.updateUserById(loaded.tpo.id, { password });
  if (error) return fail(400, error.message);
  return json({ ok: true });
}

async function setTpoStatus(admin: Admin, caller: Caller, body: Record<string, unknown>) {
  const status = body.status;
  if (status !== "active" && status !== "inactive") return fail(400, "status must be active or inactive");
  const loaded = await loadTpo(admin, caller, str(body.tpo_id));
  if (loaded.error) return loaded.error;
  return await switchStatus(admin, "tpo", loaded.tpo.id, loaded.tpo.status, status);
}
